spring:
 profiles:
  active: dev 
  datasource:
    url: jdbc:h2:mem:testdb
    username: hitesh
    password: hitesh
    driverClassName: org.h2.Driver
  jpa:
   show-sql: true
   hibernate:
    ddl-auto: none
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect 
