spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: hitesh
    password: hitesh
    driverClassName: org.h2.Driver
    jpa:
     show-sql: true
     hibernate:
      ddl-auto: none
     database-platform: org.hibernate.dialect.H2Dialect
    
welcome:
 message: Hello Hitesh from dev property config server
