eureka:
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: hitesh
    password: hitesh
    driverClassName: org.h2.Driver
    jpa:
     show-sql: true
     hibernate:
      ddl-auto: none
     database-platform: org.hibernate.dialect.H2Dialect
   h2:
    console:
      enabled: true
     
welcome:
 message: Hello Hitesh from QA property config server
